# Specifying features here will ENABLE them as long as they aren't under disabledFeatures
enabledFeatures: ["nameColouring", "softSpectator", "playerReviving"]
# Specifying features here will DISABLE them as long as they aren't under enabledFeatures
disabledFeatures: []

# Feature-specific settings
featureSettings:
  nameColouring:
    lightGreenMHP: 40
    darkGreenMHP: 20
    yellowMHP: 10
    goldMHP: 3
    redMHP: 0